apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: frontend
spec:
  selector:
    matchLabels:
      app: rabbitmq
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: frontend
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest
          ports:
            - name: porta-rabbitmq
              containerPort: 5672
            - name: porta-rabbitmq-web
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "postech"
            - name: RABBITMQ_DEFAULT_PASS
              value: "Postech123"
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - general
