apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - name: rabbitmq-amqp
              containerPort: 5672
            - name: rabbitmq-web
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "postech"
            - name: RABBITMQ_DEFAULT_PASS
              value: "Postech123456"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - general
