---
apiVersion: v1
kind: Service
metadata:
  name: produto-private-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: produto
  ports:
    - name: porta-produto
      protocol: TCP
      port: 8081
      targetPort: porta-produto
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: produto-public-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: produto
  ports:
    - name: porta-produto
      protocol: TCP
      port: 8081
      targetPort: porta-produto
  type: LoadBalancer
