# This is a basic workflow to help you get started with Actions

name: Pipeline

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    terraform-init:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            - name: Inicializa o terraform
              run: terraform init

    terraform-apply:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        needs: terraform-init

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            - name: Executa o script
              run: terraform apply

    access-aws-instance:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        needs: terraform-apply

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            - name: Acessar instância EKS
              run:  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
                    && unzip awscliv2.zip \
                    && sudo ./aws/install \
                    && aws eks --region us-east-1 update-kubeconfig --name postech

    deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        needs: access-aws-instance

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
            - name: Fazer o deploy
              run: kubectl apply -f ~/k8s/deployment.yaml \
                   && kubectl apply -f ~/k8s/public-lb.yaml \
                   && kubectl apply -f ~/k8s/private-lb.yaml
